# Generated by Django 5.1.2 on 2024-11-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_category_designrequest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.category'),
        ),
    ]
